Repository awslabs/sockeye, pull requests merged in 2018-05, with the labels that each got.

#371 Learning Hidden Unit Contribution (LHUC)
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/constants.py
  sockeye/decoder.py
  sockeye/layers.py
  sockeye/model.py
  sockeye/rnn.py
  sockeye/train.py
  sockeye/training.py
  test/integration/test_seq_copy_int.py
  test/unit/test_arguments.py
  test/unit/test_layers.py
Labels: feature

#379 Removed tensorboard logging of embedding & output parameters at every…
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/training.py
Labels: enhancement

#375 Avoid recreating partial for topk with every request in inference
  sockeye/inference.py
Labels: enhancement

#382 Bugfix: Make sure lhuc flag is passed as bool to configs
  CHANGELOG.md
  sockeye/train.py
Labels: bug

#384 Remove overly restrictive check to support early stopping with BLEU
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/training.py
Labels: bug

#387 proper none check for lhuc
  sockeye/layers.py
Labels: bug

#376 Simplified computation of smoothed cross entropy loss in CrossEntropyMetric
  sockeye/loss.py
  test/unit/test_loss.py
Labels: enhancement

#374 experimental option to override transformer dtype during inference
  sockeye/arguments.py
  sockeye/constants.py
  sockeye/decoder.py
  sockeye/encoder.py
  sockeye/inference.py
  sockeye/rnn_attention.py
  sockeye/transformer.py
  sockeye/translate.py
  sockeye/utils.py
  test/unit/test_arguments.py
  test/unit/test_operator.py
Labels: feature

#381 Updating default parameters with values from our arXiv paper.
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/constants.py
  test/integration/test_seq_copy_int.py
  test/system/test_seq_copy_sys.py
  test/unit/test_arguments.py
  tutorials/README.md
  tutorials/wmt/README.md
Labels: enhancement

#392 Adding an end of sentence symbol to the source side.
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/constants.py
  sockeye/data_io.py
  sockeye/inference.py
  sockeye/prepare_data.py
  sockeye/train.py
  test/integration/test_seq_copy_int.py
  test/system/test_seq_copy_sys.py
  test/unit/test_arguments.py
  test/unit/test_data_io.py
Labels: enhancement

#396 Fix Sphinx 1.7.4 build (as run by readthedocs.io).
  docs/conf.py
  docs/modules.rst
  requirements.docs.txt
  sockeye/encoder.py
  sockeye/inference.py
  sockeye/layers.py
  sockeye/lexicon.py
Labels: enhancement

#398 Removed separate beam prune system test and added pruning to another …
  sockeye/inference.py
  test/system/test_seq_copy_sys.py
Labels: enhancement

#399 Argument specifications for each CLI are now stored in a static structure.
  sockeye/arguments.py
  sockeye/average.py
  sockeye/embeddings.py
  sockeye/extract_parameters.py
  sockeye/init_embedding.py
  sockeye/prepare_data.py
  sockeye/train.py
  sockeye/translate.py
Labels: enhancement

#401 Update development.md
  docs/development.md
Labels: enhancement

#402 Added support for config files
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/constants.py
  sockeye/train.py
  sockeye/translate.py
  test/unit/test_arguments.py
Labels: feature

#404 Fix logic with training resumption
  CHANGELOG.md
  sockeye/data_io.py
  sockeye/training.py
Labels: bug

#349 Added hard lexical constraints (Post & Vilar, NAACL 2018)
  CHANGELOG.md
  docs/modules.rst
  sockeye/__init__.py
  sockeye/constants.py
  sockeye/inference.py
  sockeye/lexical_constraints.py
  sockeye/translate.py
  test/common.py
  test/integration/test_seq_copy_int.py
  test/unit/test_constraints.py
  test/unit/test_output_handler.py
  test/unit/test_translate.py
  tutorials/constraints/README.md
  typechecked-files
Labels: feature

#407 Removed summation of gradient arrays when logging gradients.
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/training.py
Labels: bug

#406 added wmt18 data sets
  contrib/sacrebleu/CHANGELOG.md
  contrib/sacrebleu/README.md
  contrib/sacrebleu/sacrebleu.py
Labels: sacrebleu

#388 Update to MXNet 1.2
  CHANGELOG.md
  README.md
  requirements.gpu-cu75.txt
  requirements.gpu-cu80.txt
  requirements.gpu-cu90.txt
  requirements.gpu-cu91.txt
  requirements.txt
  sockeye/__init__.py
  sockeye/coverage.py
  sockeye/decoder.py
  sockeye/layers.py
  sockeye/rnn.py
  sockeye/rnn_attention.py
  sockeye/transformer.py
  test/unit/test_coverage.py
  test/unit/test_layers.py
  test/unit/test_rnn.py
Labels: enhancement

#412 Removed some unused code in inference.
  sockeye/inference.py
  sockeye/lexical_constraints.py
Labels: enhancement

#417 Small cleanup in inference regarding data types, copy vs assignment and some reordering
  sockeye/inference.py
Labels: enhancement

#418 Remove unused argument from Transformer pre/post process blocks
  sockeye/decoder.py
  sockeye/encoder.py
  sockeye/transformer.py
Labels: enhancement

#419 Allow specifying different transformer parameters for encoder and decoder
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/train.py
  test/unit/test_arguments.py
Labels: enhancement

#328 Add beam visualization
  contrib/vistools/README.md
  contrib/vistools/generate_graphs.py
  contrib/vistools/pytest.ini
  contrib/vistools/requirements.txt
  contrib/vistools/templates/tree.css
  contrib/vistools/templates/tree.js
  contrib/vistools/test/__init__.py
  contrib/vistools/test/resources/beams.json
  contrib/vistools/test/resources/output/000000.html
  contrib/vistools/test/resources/output/000001.html
  contrib/vistools/test/resources/output/000002.html
  contrib/vistools/test/resources/output/000003.html
  contrib/vistools/test/resources/output/000004.html
  contrib/vistools/test/resources/output/000005.html
  contrib/vistools/test/resources/output/000006.html
  contrib/vistools/test/resources/output/000007.html
  contrib/vistools/test/resources/output/000008.html
  contrib/vistools/test/resources/output/000009.html
  contrib/vistools/test/resources/output/tree.css
  contrib/vistools/test/resources/output/tree.js
  contrib/vistools/test/test_integration.py
Labels: feature

#422 Avoid function with side effect in inference
  sockeye/inference.py
Labels: enhancement

#423 Refactored pruning logic and vectorized it
  sockeye/inference.py
  sockeye/utils.py
  test/unit/test_inference.py
Labels: enhancement
