Repository awslabs/sockeye, pull requests merged in 2018-12, with the labels that each got.

#590 Informative error message when --max-seq-len is too small.
  sockeye/arguments.py
  sockeye/constants.py
  sockeye/data_io.py
  sockeye/score.py
Labels: enhancement

#586 sampling
  CHANGELOG.md
  docs/inference.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/inference.py
  sockeye/lexical_constraints.py
  sockeye/translate.py
  sockeye/utils.py
  test/unit/test_arguments.py
  test/unit/test_inference.py
Labels: feature

#592 Move compatibility checks for inference configuration variables into API functions (Translator.init() & load_models())
  sockeye/inference.py
  sockeye/lexical_constraints.py
  sockeye/translate.py
  sockeye/utils.py
Labels: enhancement

#594 Fix BLEU score for decodings with restrict-lexicon in system tests
  test/common.py
  test/system/test_seq_copy_sys.py
Labels: bug

#611 Add an option to keep the first checkpoint, in addition to the last n checkpoints
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/image_captioning/train.py
  sockeye/train.py
  sockeye/training.py
  sockeye/utils.py
  test/unit/test_arguments.py
  test/unit/test_params.py
Labels: feature

#612 Add fertility to count coverage
  CHANGELOG.md
  sockeye/arguments.py
  sockeye/constants.py
  sockeye/coverage.py
  sockeye/train.py
  test/unit/test_arguments.py
  test/unit/test_attention.py
  test/unit/test_coverage.py
  test/unit/test_decoder.py
Labels: feature
