Repository awslabs/sockeye, pull requests merged in 2018-03, with the labels that each got.

#307 Use stack instead of expand_dims, concat for memory efficiency.
  CHANGELOG.md
  sockeye/coverage.py
  sockeye/decoder.py
  sockeye/encoder.py
  sockeye/rnn_attention.py
Labels: enhancement

#316 Support for evaluating multiple hypothesis.
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/evaluate.py
Labels: feature

#304 Separate TrainingModel into TrainingModel and EarlyStoppingTrainer classes.
  sockeye/callback.py
  sockeye/checkpoint_decoder.py
  sockeye/constants.py
  sockeye/inference.py
  sockeye/lr_scheduler.py
  sockeye/model.py
  sockeye/optimizers.py
  sockeye/train.py
  sockeye/training.py
  sockeye/utils.py
  test/unit/test_callback.py
  test/unit/test_params.py
  test/unit/test_utils.py
  typechecked-files
Labels: enhancement

#319 Updated embeddings inspection CLI to support weight tying
  sockeye/embeddings.py
  tutorials/wmt/README.md
Labels: enhancement

#317 Bug when loading external parameters for initialization
  sockeye/training.py
Labels: bug

#320 Fix params
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/init_embedding.py
  sockeye/model.py
  sockeye/train.py
  sockeye/training.py
  test/unit/test_arguments.py
Labels: feature

#322 Added option --dry-run (light version)
  CHANGELOG.md
  sockeye/arguments.py
  sockeye/train.py
  test/unit/test_arguments.py
Labels: feature

#324 [1.18] Change default target vocab name in model folder to vocab.trg.0.json
  CHANGELOG.md
  sockeye/constants.py
  sockeye/data_io.py
  sockeye/embeddings.py
  sockeye/inference.py
  sockeye/lexicon.py
  sockeye/train.py
  sockeye/vocab.py
Labels: backwards_incompatible

#311 [1.18] restrict-lexicon: Allow specification of topk at runtime.
  CHANGELOG.md
  sockeye/arguments.py
  sockeye/lexicon.py
  sockeye/translate.py
  test/common.py
  test/unit/test_arguments.py
  test/unit/test_lexicon.py
Labels: backwards_incompatible, feature

#333 Mxnet topk unless cpu
  sockeye/inference.py
Labels: enhancement

#315 rnn_attention config and factory improvements
  sockeye/arguments.py
  sockeye/constants.py
  sockeye/rnn_attention.py
  sockeye/train.py
  test/unit/test_arguments.py
  test/unit/test_attention.py
Labels: enhancement

#336 Make sure all model parameters are prefixed by a model prefix. Default: ''
  sockeye/decoder.py
  sockeye/encoder.py
  sockeye/model.py
  sockeye/rnn_attention.py
  sockeye/training.py
Labels: enhancement
