Repository awslabs/sockeye, pull requests merged in 2018-02, with the labels that each got.

#297 added chrf signature; removed locale dependency
  contrib/sacrebleu/README.md
  contrib/sacrebleu/__init__.py
  contrib/sacrebleu/sacrebleu.py
  contrib/sacrebleu/test.sh
  sockeye/evaluate.py
Labels: sacrebleu

#296 Remove bias parameters in Transformer attention layers as they bring no benefit
  CHANGELOG.md
  sockeye/layers.py
Labels: backwards_incompatible

#299 Explicit dependency on DMLC tensorboard fork
  README.md
  docs/user_documentation.md
  setup.py
  tutorials/wmt/README.md
Labels: enhancement

#275 Source factors
  CHANGELOG.md
  README.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/checkpoint_decoder.py
  sockeye/constants.py
  sockeye/data_io.py
  sockeye/embeddings.py
  sockeye/encoder.py
  sockeye/inference.py
  sockeye/layers.py
  sockeye/lexicon.py
  sockeye/log.py
  sockeye/model.py
  sockeye/output_handler.py
  sockeye/prepare_data.py
  sockeye/train.py
  sockeye/training.py
  sockeye/translate.py
  sockeye/utils.py
  sockeye/vocab.py
  test/common.py
  test/integration/test_seq_copy_int.py
  test/system/test_seq_copy_sys.py
  test/unit/test_arguments.py
  test/unit/test_data_io.py
  test/unit/test_inference.py
  test/unit/test_output_handler.py
  test/unit/test_translate.py
Labels: backwards_incompatible

#300 Update to MXNet 1.1.0
  CHANGELOG.md
  README.md
  requirements.gpu-cu75.txt
  requirements.gpu-cu80.txt
  requirements.gpu-cu90.txt
  requirements.txt
  sockeye/__init__.py
  sockeye/convolution.py
  sockeye/coverage.py
  sockeye/decoder.py
  sockeye/rnn_attention.py
  test/unit/test_coverage.py
  test/unit/test_utils.py
Labels: enhancement

#285 Store beam search history
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/constants.py
  sockeye/inference.py
  sockeye/output_handler.py
  sockeye/translate.py
  test/unit/test_output_handler.py
Labels: feature

#306 Renamed pre-commit.sh to style-check.sh and clarified PR instructions.
  .github/PULL_REQUEST_TEMPLATE.md
  pre-commit.sh
  style-check.sh
Labels: enhancement
