Repository awslabs/sockeye, pull requests merged in 2018-06, with the labels that each got.

#425 Refactor beam search to use gluon hybrid blocks
  sockeye/inference.py
  sockeye/utils.py
  test/unit/test_inference.py
  test/unit/test_utils.py
Labels: enhancement

#430 Fix: Word based batching memory with longer source sentences.
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/data_io.py
  test/unit/test_data_io.py
Labels: bug

#444 Avoid NDArray indexing in inference.
  sockeye/inference.py
Labels: enhancement

#454 Use version of NDArray split that always returns a list.
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/inference.py
  sockeye/utils.py
  test/unit/test_utils.py
Labels: bug

#361 add Multi-instance translate chapter in README and its script example
  tutorials/README.md
  tutorials/process_per_core_translation/README.md
  tutorials/process_per_core_translation/cpu_process_per_core_translation.py
Labels: WIP
