Repository awslabs/sockeye, pull requests merged in 2018-04, with the labels that each got.

#353 Added Cuda9.1 requirements file
  README.md
  requirements.gpu-cu91.txt
Labels: enhancement

#356 Increased test coverage of integration tests by adding checkpoint dec…
  sockeye/checkpoint_decoder.py
  test/common.py
  test/integration/test_seq_copy_int.py
Labels: enhancement

#360 Transformer source attention: removed combined linear projection for keys & values
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/layers.py
  sockeye/utils.py
Labels: enhancement

#338 Batched top-k implementation
  CHANGELOG.md
  sockeye/inference.py
  sockeye/utils.py
Labels: enhancement

#362 Allow empty sequences in train/validation data and skip them
  .gitignore
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/data_io.py
  test/unit/test_data_io.py
Labels: feature

#368 Ensure last checkpoint decoder results are written to metrics fail wh…
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/training.py
Labels: bug

#369 Proper reloading of learning rate scheduler state at training resumption
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/optimizers.py
  sockeye/train.py
  sockeye/training.py
Labels: bug

#373 Log loading time of models and topklexicon at inference
  sockeye/inference.py
  sockeye/lexicon.py
Labels: enhancement
