Repository awslabs/sockeye, pull requests merged in 2019-04, with the labels that each got.

#657 Update to MXNet 1.4.0
  CHANGELOG.md
  docs/setup.md
  requirements/requirements.gpu-cu100.txt
  requirements/requirements.gpu-cu80.txt
  requirements/requirements.gpu-cu90.txt
  requirements/requirements.gpu-cu92.txt
  requirements/requirements.txt
  sockeye/__init__.py
  sockeye/constants.py
  sockeye/inference.py
  test/common.py
  test/integration/test_seq_copy_int.py
  test/system/test_seq_copy_sys.py
Labels: enhancement

#672 Change sacrebleu call to use pip-installed sacrebleu
  sockeye_contrib/autopilot/autopilot.py
Labels: autopilot

#677 Support multiple lexicons for vocabulary selection
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/constants.py
  sockeye/image_captioning/inference.py
  sockeye/inference.py
  sockeye/translate.py
  test/unit/test_inference.py
Labels: feature

#626 Length ratio prediction
  CHANGELOG.md
  docs/inference.md
  docs/training.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/checkpoint_decoder.py
  sockeye/constants.py
  sockeye/evaluate.py
  sockeye/image_captioning/captioner.py
  sockeye/image_captioning/checkpoint_decoder.py
  sockeye/image_captioning/data_io.py
  sockeye/image_captioning/inference.py
  sockeye/inference.py
  sockeye/layers.py
  sockeye/loss.py
  sockeye/model.py
  sockeye/score.py
  sockeye/scoring.py
  sockeye/train.py
  sockeye/training.py
  sockeye/translate.py
  test/common.py
  test/integration/test_seq_copy_int.py
  test/system/test_seq_copy_sys.py
  test/unit/test_arguments.py
  test/unit/test_inference.py
  test/unit/test_layers.py
  test/unit/test_loss.py
Labels: feature

#680 Change brevity penalty parameter of Translator to be entirely optiona…
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/inference.py
  sockeye/translate.py
Labels: enhancement

#673 Gradient accumulation over multiple batches.
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/optimizers.py
  sockeye/train.py
  sockeye/training.py
  test/system/test_seq_copy_sys.py
  test/unit/test_arguments.py
Labels: feature

#681 Removed custom operators from transformer models
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/decoder.py
  sockeye/encoder.py
  sockeye/layers.py
  sockeye/transformer.py
  test/unit/test_operator.py
Labels: enhancement
