Repository awslabs/sockeye, pull requests merged in 2019-02, with the labels that each got.

#642 Disable dropout layers in inference
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/config.py
  sockeye/inference.py
Labels: enhancement

#593 rewrote scoring to load data on demand and not skip sentences
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/constants.py
  sockeye/data_io.py
  sockeye/encoder.py
  sockeye/image_captioning/data_io.py
  sockeye/image_captioning/train.py
  sockeye/log.py
  sockeye/score.py
  sockeye/scoring.py
  sockeye/train.py
  test/common.py
  test/unit/image_captioning/test_data_io.py
  test/unit/test_arguments.py
  test/unit/test_data_io.py
Labels: enhancement

#641 Refactored batch_size in InferenceModel and Translator to allow for dynamic batch sizes
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/image_captioning/inference.py
  sockeye/inference.py
  sockeye/log.py
  sockeye/score.py
  sockeye/train.py
  sockeye/translate.py
  sockeye/utils.py
  test/unit/test_arguments.py
  test/unit/test_inference.py
  test/unit/test_translate.py
Labels: enhancement, feature

#646 Detect divergence and report it with the convergence status in the metrics file
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/train.py
  sockeye/training.py
  sockeye/utils.py
Labels: bug, feature
