Repository awslabs/sockeye, pull requests merged in 2019-01, with the labels that each got.

#624 fix pytest-cov to 2.6.0 for Travis
  requirements/requirements.dev.txt
  sockeye/image_captioning/utils.py
Labels: enhancement

#623 Correctly use initial optimizer states on learning rate decay
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/training.py
Labels: bug

#622 Added summing of source factors
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/arguments.py
  sockeye/constants.py
  sockeye/encoder.py
  sockeye/train.py
  test/integration/test_seq_copy_int.py
  test/unit/test_arguments.py
Labels: feature

#627 added ability to carry over extra fields in JSON input
  CHANGELOG.md
  docs/inference.md
  docs/training.md
  sockeye/__init__.py
  sockeye/constants.py
  sockeye/inference.py
  sockeye/output_handler.py
  sockeye/translate.py
  test/unit/test_output_handler.py
Labels: feature

#601 Refactored run_train_translate function for integration and system testing
  sockeye/arguments.py
  sockeye/constants.py
  sockeye/inference.py
  test/common.py
  test/integration/image_captioning/test_image_captioning.py
  test/integration/test_constraints_int.py
  test/integration/test_seq_copy_int.py
  test/system/test_seq_copy_sys.py
  test/unit/test_data_io.py
Labels: enhancement

#631 Ensure backwards compatibility for models with source-factor-combine concat
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/encoder.py
Labels: bug

#630 Replaced expand_dims with reshape ops to avoid data copies
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/convolution.py
  sockeye/coverage.py
  sockeye/decoder.py
  sockeye/encoder.py
  sockeye/inference.py
  sockeye/layers.py
  sockeye/rnn_attention.py
Labels: enhancement

#634 Fix check and automatic setting of source_factors_num_embed when comb…
  CHANGELOG.md
  sockeye/__init__.py
  sockeye/train.py
Labels: bug
